# Generated by Django 3.2 on 2021-06-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_loanoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanoffer',
            name='user',
        ),
        migrations.AddField(
            model_name='loanoffer',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='request.loanrequest'),
            preserve_default=False,
        ),
    ]
