# Generated by Django 3.2 on 2021-06-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20210620_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoffer',
            name='status',
            field=models.CharField(choices=[('Notselected', 'Default'), ('Approved', 'Approved'), ('Refused', 'Refused')], default='Notselected', max_length=50),
        ),
    ]
